---
name: Darcs-Notify
version: 1.0
author:
  - 'David Caldwell <david@porkrind.org>'
abstract: Send emails when a Darcs repository has patches added or removed
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Darcs::Inventory: 1.0
  IPC::Run: 0
provides:
  Darcs::Notify:
    file: lib/Darcs/Notify.pm
    version: 1.0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
